name: Feature Request
description: Suggest a new feature for the project.
title: "[FEATURE REQUEST]"
labels: feature request
body:
  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: Select the topic of your feature request.
      options:
        - User Interface
        - Performance
        - Security
        - Documentation
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Select the platform for which you are requesting the feature.
      options:
        - Android
        - iOS/iPadOS
        - CLI
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Specify the version of the app you are using
  - type: input
    id: build
    attributes:
      label: Build Number
      description: Specify the build number of the app you are using
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the feature you are requesting.
    validations:
      required: true
