package net.extrawdw.notisync.protocol.crypto

import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import net.extrawdw.notisync.protocol.AssetAad
import net.extrawdw.notisync.protocol.AssetRole
import net.extrawdw.notisync.protocol.CipherSuite
import net.extrawdw.notisync.protocol.ClientId
import net.extrawdw.notisync.protocol.ClientKeyEpoch
import net.extrawdw.notisync.protocol.DismissEvent
import net.extrawdw.notisync.protocol.Envelope
import net.extrawdw.notisync.protocol.EnvelopeAuth
import net.extrawdw.notisync.protocol.MessageType
import net.extrawdw.notisync.protocol.ProtocolCodec
import net.extrawdw.notisync.protocol.Purpose
import net.extrawdw.notisync.protocol.SignedBlob
import net.extrawdw.notisync.protocol.SignedType
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.util.Base64

/**
 * Phase 0 of the iOS plan: generate the Kotlin→Swift golden vectors and assert their self-consistency
 * on the JVM so this doubles as a regression guard. The emitted JSON file is consumed by the iOS
 * XCTest suite (Phases 2–3) to prove the native Swift crypto is byte-compatible with this reference
 * implementation. See ~/.claude/plans/read-docs-notisync-ios-library-implement-giggly-sky.md §B.5 / §E.
 *
 * The two byte-identity vectors ([EnvelopeAuth], [AssetAad]) are built from fixed literal inputs so the
 * expected CBOR is stable; everything else embeds the (possibly freshly generated) keys it needs so the
 * file is self-contained. Binary fields are base64-standard (Swift: `Data(base64Encoded:)`).
 *
 * The HPKE vectors are the Tink↔CryptoKit framing proof obligation: Kotlin seals via [Hpke.sealToRaw]
 * to the RFC-7748 §6.1 X25519 keypair (whose raw private key is published in the vector), and Swift
 * must open them with CryptoKit `HPKE.Recipient`. If those open, NS2's `NO_PREFIX` Tink output is the
 * bare RFC-9180 `enc‖ct` the plan assumes.
 */
class GoldenVectorsTest {

    private fun ByteArray.b64(): String = Base64.getEncoder().encodeToString(this)
    private fun hex(s: String): ByteArray =
        s.chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    // RFC 7748 §6.1 — Alice's X25519 keypair. The raw private (seed) is known, so Swift/CryptoKit can
    // reconstruct it (`Curve25519.KeyAgreement.PrivateKey(rawRepresentation:)`) and open Tink-sealed bytes.
    private val rfc7748PrivX25519 = hex("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
    private val rfc7748PubX25519 = hex("8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")

    private val out = Json { prettyPrint = true; encodeDefaults = true }

    @Test
    fun generateGoldenVectors() {
        val file = GoldenFile(
            note = "NotiSync Kotlin→Swift golden vectors. Binary fields are base64-standard. " +
                "Generated by GoldenVectorsTest; consumed by the iOS XCTest suite.",
            suite = CipherSuite.CURRENT_ID,
            byteEncoding = "base64-standard",
            clientId = clientIdVector(),
            envelopeAuthCbor = envelopeAuthVector(),
            assetAadCbor = assetAadVector(),
            httpSign = httpSignVector(),
            keyEpochFull = keyEpochVector(stripped = false),
            keyEpochStripped = keyEpochVector(stripped = true),
            keyEpochTampered = keyEpochTamperedVector(),
            hpkeSealToRaw = hpkeSealToRawVector(),
            envelopeOpen = envelopeOpenVector(),
        )

        val json = out.encodeToString(file)
        val target = System.getProperty("notisync.vectors.out")
            ?.let { File(it) }
            ?: File("build/golden-vectors/notisync-golden.json")
        target.parentFile?.mkdirs()
        target.writeText(json)
        println("[golden-vectors] wrote ${file.vectorCount()} vectors -> ${target.absolutePath} (${json.length} bytes)")
    }

    // 1. clientId = base32(sha256(identity SPKI)[..20]).
    private fun clientIdVector(): ClientIdVec {
        val signer = SoftwareIdentitySigner.generate()
        val derived = ClientIds.derive(signer.publicKeySpki)
        assertEquals(signer.clientId, derived)
        assertEquals(32, derived.value.length)
        return ClientIdVec(identitySpki = signer.publicKeySpki.b64(), expectedClientId = derived.value)
    }

    // 2. EnvelopeAuth CBOR — byte-identity gate. Fixed literal inputs → stable expected bytes.
    private fun envelopeAuthVector(): ByteIdentityVec {
        val auth = EnvelopeAuth(
            v = 1,
            suite = "NS2",
            typ = MessageType.NOTIFICATION,
            signerId = ClientId("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
            signerEpoch = 1,
            messageId = "01J0GOLDEN0ENVELOPE0AUTH0",
            seq = 42L,
            createdAt = 1_750_000_000_000L,
            bodyCiphertextSha256 = ByteArray(32) { it.toByte() },
            recipientIds = listOf(
                ClientId("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
                ClientId("cccccccccccccccccccccccccccccccc"),
            ),
            recipientEpochs = listOf(1, 2),
        )
        val cbor = ProtocolCodec.encodeToCbor(auth)
        // Round-trips on the JVM (re-encode the decoded value; data-class equals can't compare the ByteArray field).
        assertArrayEquals(cbor, ProtocolCodec.encodeToCbor(ProtocolCodec.decodeFromCbor<EnvelopeAuth>(cbor)))
        return ByteIdentityVec(
            description = "EnvelopeAuth with fixed fields; Swift must encode CBOR byte-identically.",
            inputsJson = out.encodeToString(EnvelopeAuthInputs(auth)),
            expectedCbor = cbor.b64(),
        )
    }

    // 3. AssetAad CBOR — byte-identity gate (re-encoded on both ends as AEAD AAD).
    private fun assetAadVector(): ByteIdentityVec {
        val aad = AssetAad(
            suite = "NS2",
            sourceClientId = ClientId("dddddddddddddddddddddddddddddddd"),
            assetId = "abcdefghijklmnopqrstuvwxyz234567",
            mimeType = "image/jpeg",
            sizeBytes = 12345,
            role = AssetRole.LARGE_ICON,
        )
        val cbor = ProtocolCodec.encodeToCbor(aad)
        assertEquals(aad, ProtocolCodec.decodeFromCbor<AssetAad>(cbor))
        return ByteIdentityVec(
            description = "AssetAad with fixed fields; Swift must encode CBOR byte-identically.",
            inputsJson = out.encodeToString(AssetAadInputs(aad)),
            expectedCbor = cbor.b64(),
        )
    }

    // 4. HTTP request signing — Swift rebuilds the canonical string and verifies the DER ECDSA signature.
    private fun httpSignVector(): HttpSignVec {
        val signer = SoftwareIdentitySigner.generate()
        val method = "POST"
        val pathAndQuery = "/v2/keyepoch"
        val body = "golden-vector-body".toByteArray()
        val nonce = "Z29sZGVuLW5vbmNlLTAwMDAwMQ"
        val ts = 1_750_000_000_000L
        val headers = HttpRequestSigning.sign(signer, method, pathAndQuery, body, nowMillis = ts, nonce = nonce)
        val canonical = HttpRequestSigning.canonical(
            method, pathAndQuery, signer.clientId, ts, nonce, headers.contentSha256, signerEpoch = 0,
        )
        assertTrue(HttpRequestSigning.verify(signer.publicKeySpki, method, pathAndQuery, body, headers))
        return HttpSignVec(
            method = method,
            pathAndQuery = pathAndQuery,
            body = body.b64(),
            clientId = signer.clientId.value,
            signerEpoch = 0,
            timestampMillis = ts,
            nonce = nonce,
            contentSha256 = headers.contentSha256,
            canonical = canonical.b64(),
            signature = headers.signature,
            signerSpki = signer.publicKeySpki.b64(),
        )
    }

    // 5/6. ClientKeyEpoch verify — full (carries its identity anchor) and stripped (pinned identity supplied).
    private fun keyEpochVector(stripped: Boolean): KeyEpochVec {
        val identity = SoftwareIdentitySigner.generate()
        val op = SoftwareOperationalSigner.generate(identity.clientId, signerEpoch = 1)
        val ke = ClientKeyEpoch(
            suite = "NS2",
            clientId = identity.clientId,
            identityPublicKey = if (stripped) ByteArray(0) else identity.publicKeySpki,
            epoch = 1,
            operationalSigningKey = op.operationalPublicKeySpki,
            hpkePublicKey = rfc7748PubX25519, // raw 32-byte X25519 (post-rename wire form)
            purposes = listOf(Purpose.ENVELOPE_SIGN, Purpose.REQUEST_AUTH, Purpose.HPKE_SEAL),
            notBefore = 1_750_000_000_000L,
            notAfter = 1_760_000_000_000L,
            minEpoch = 1,
        )
        val payload = ProtocolCodec.encodeToCbor(ke)
        val blob = SignedBlob(
            typ = SignedType.KEY_EPOCH,
            signerId = identity.clientId,
            payload = payload,
            sig = identity.sign(payload),
        )
        // Reference-side check: verify exactly as a peer would (field-wise; data-class equals can't compare ByteArrays).
        val pin = if (stripped) identity.publicKeySpki else null
        val verified = requireNotNull(KeyEpochs.verify(blob, pin)) { "reference key-epoch must verify" }
        assertEquals(ke.clientId, verified.clientId)
        assertEquals(ke.epoch, verified.epoch)
        assertArrayEquals(ke.operationalSigningKey, verified.operationalSigningKey)
        assertArrayEquals(ke.hpkePublicKey, verified.hpkePublicKey)
        return KeyEpochVec(
            description = if (stripped) "Stripped epoch: identityPublicKey empty; verify against pinnedIdentitySpki."
            else "Full epoch: self-contained identity anchor.",
            signedBlobCbor = ProtocolCodec.encodeToCbor(blob).b64(),
            pinnedIdentitySpki = if (stripped) identity.publicKeySpki.b64() else null,
            expectedClientId = identity.clientId.value,
            expectedEpoch = 1,
            expectedOperationalSpki = op.operationalPublicKeySpki.b64(),
            expectedHpkePublicKey = rfc7748PubX25519.b64(),
        )
    }

    // 7. Negative: a tampered key-epoch blob must NOT verify (flipped a payload byte after signing).
    private fun keyEpochTamperedVector(): KeyEpochNegVec {
        val identity = SoftwareIdentitySigner.generate()
        val op = SoftwareOperationalSigner.generate(identity.clientId, signerEpoch = 1)
        val ke = ClientKeyEpoch(
            suite = "NS2", clientId = identity.clientId, identityPublicKey = identity.publicKeySpki, epoch = 1,
            operationalSigningKey = op.operationalPublicKeySpki, hpkePublicKey = rfc7748PubX25519,
            purposes = listOf(Purpose.ENVELOPE_SIGN), notBefore = 0, notAfter = 1_760_000_000_000L, minEpoch = 1,
        )
        val payload = ProtocolCodec.encodeToCbor(ke)
        val sig = identity.sign(payload)
        val tampered = payload.copyOf().also { it[it.size - 1] = (it[it.size - 1].toInt() xor 0x01).toByte() }
        val blob = SignedBlob(SignedType.KEY_EPOCH, "NS2", identity.clientId, tampered, sig)
        assertNull("tampered key-epoch must not verify", KeyEpochs.verify(blob, null))
        return KeyEpochNegVec(
            description = "Tampered payload (one flipped byte) under a valid signature → verify returns null/false.",
            signedBlobCbor = ProtocolCodec.encodeToCbor(blob).b64(),
        )
    }

    // 8. HPKE seal-to-raw — Kotlin (Tink) seals a DEK to the RFC-7748 raw X25519 key; Swift opens with CryptoKit.
    private fun hpkeSealToRawVector(): HpkeRawVec {
        val dek = ByteArray(32) { (it * 7 + 1).toByte() }
        val info = "notisync:dek:NS2|eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee|1".toByteArray()
        val sealed = Hpke.sealToRaw(dek, rfc7748PubX25519, info)
        // enc(32) ‖ aeadCt — sanity on the framing length.
        assertTrue("sealed must be enc(32)+ct+tag", sealed.size >= 32 + dek.size + 16)
        return HpkeRawVec(
            description = "Tink NO_PREFIX seal to a raw X25519 key. Swift: split enc=[0..<32], " +
                "HPKE.Recipient(privateKey: rfc7748Priv, info: info, encapsulationKey: enc).open(ct) == expectedDek.",
            recipientPrivX25519 = rfc7748PrivX25519.b64(),
            recipientPubX25519 = rfc7748PubX25519.b64(),
            info = info.b64(),
            sealedDek = sealed.b64(),
            expectedDek = dek.b64(),
        )
    }

    // 9. Full envelope open — operational-signed envelope sealed to the RFC-7748 recipient; Swift verifies + opens.
    private fun envelopeOpenVector(): EnvelopeOpenVec {
        val identity = SoftwareIdentitySigner.generate()
        val op = SoftwareOperationalSigner.generate(identity.clientId, signerEpoch = 1)
        val recipientId = ClientId("eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
        val recipientEpoch = 1
        val body = ProtocolCodec.encodeToCbor(
            DismissEvent(sourceClientId = identity.clientId, sourceKey = "0|com.example.chat|7|null", dismissedAt = 1_750_000_000_500L)
        )
        val env = EnvelopeCrypto.seal(
            signer = op,
            typ = MessageType.DISMISSAL,
            bodyPlaintext = body,
            recipients = listOf(RecipientKey(recipientId, rfc7748PubX25519, recipientEpoch)),
            messageId = "01J0GOLDEN0ENVELOPE0OPEN0",
            seq = 7L,
            createdAt = 1_750_000_000_000L,
            suite = "NS2",
        )
        assertTrue(EnvelopeCrypto.verify(env, op.operationalPublicKeySpki))
        return EnvelopeOpenVec(
            description = "Operational-signed DISMISSAL envelope sealed to the RFC-7748 recipient. Swift: " +
                "verify sig vs operationalSpki, HPKE-open the matching recipient's sealedDek with rfc7748Priv " +
                "(info = notisync:dek:NS2|<recipientId>|<recipientEpoch>), then AES-GCM-open the body " +
                "(aad = notisync:body:NS2) == expectedBody.",
            envelopeCbor = ProtocolCodec.encodeToCbor(env).b64(),
            operationalSpki = op.operationalPublicKeySpki.b64(),
            recipientId = recipientId.value,
            recipientEpoch = recipientEpoch,
            recipientPrivX25519 = rfc7748PrivX25519.b64(),
            dekContext = "notisync:dek:NS2|${recipientId.value}|$recipientEpoch",
            bodyAad = "notisync:body:NS2",
            expectedBody = body.b64(),
            expectedDismissSourceKey = "0|com.example.chat|7|null",
        )
    }

    // ---- vector JSON schema (mirrored by the Swift decoder) ----
    @Serializable
    private data class GoldenFile(
        val note: String,
        val suite: String,
        val byteEncoding: String,
        val clientId: ClientIdVec,
        val envelopeAuthCbor: ByteIdentityVec,
        val assetAadCbor: ByteIdentityVec,
        val httpSign: HttpSignVec,
        val keyEpochFull: KeyEpochVec,
        val keyEpochStripped: KeyEpochVec,
        val keyEpochTampered: KeyEpochNegVec,
        val hpkeSealToRaw: HpkeRawVec,
        val envelopeOpen: EnvelopeOpenVec,
    ) {
        fun vectorCount() = 10
    }

    @Serializable private data class ClientIdVec(val identitySpki: String, val expectedClientId: String)
    @Serializable private data class ByteIdentityVec(val description: String, val inputsJson: String, val expectedCbor: String)
    @Serializable private data class EnvelopeAuthInputs(
        val v: Int, val suite: String, val typ: String, val signerId: String, val signerEpoch: Int,
        val messageId: String, val seq: Long, val createdAt: Long, val bodyCiphertextSha256: String,
        val recipientIds: List<String>, val recipientEpochs: List<Int>,
    ) {
        constructor(a: EnvelopeAuth) : this(
            a.v, a.suite, a.typ.name, a.signerId.value, a.signerEpoch, a.messageId, a.seq, a.createdAt,
            Base64.getEncoder().encodeToString(a.bodyCiphertextSha256), a.recipientIds.map { it.value }, a.recipientEpochs,
        )
    }
    @Serializable private data class AssetAadInputs(
        val suite: String, val sourceClientId: String, val assetId: String, val mimeType: String,
        val sizeBytes: Int, val role: String,
    ) {
        constructor(a: AssetAad) : this(a.suite, a.sourceClientId.value, a.assetId, a.mimeType, a.sizeBytes, a.role.name)
    }
    @Serializable private data class HttpSignVec(
        val method: String, val pathAndQuery: String, val body: String, val clientId: String, val signerEpoch: Int,
        val timestampMillis: Long, val nonce: String, val contentSha256: String, val canonical: String,
        val signature: String, val signerSpki: String,
    )
    @Serializable private data class KeyEpochVec(
        val description: String, val signedBlobCbor: String, val pinnedIdentitySpki: String?,
        val expectedClientId: String, val expectedEpoch: Int, val expectedOperationalSpki: String,
        val expectedHpkePublicKey: String,
    )
    @Serializable private data class KeyEpochNegVec(val description: String, val signedBlobCbor: String)
    @Serializable private data class HpkeRawVec(
        val description: String, val recipientPrivX25519: String, val recipientPubX25519: String,
        val info: String, val sealedDek: String, val expectedDek: String,
    )
    @Serializable private data class EnvelopeOpenVec(
        val description: String, val envelopeCbor: String, val operationalSpki: String, val recipientId: String,
        val recipientEpoch: Int, val recipientPrivX25519: String, val dekContext: String, val bodyAad: String,
        val expectedBody: String, val expectedDismissSourceKey: String,
    )
}
